# Development environment
development:
  password:
  theme_id:
  store: your-shop.myshopify.com
  ignore_files:
    settings_data.json
    mix-manifest.json

# Production environment
production:
  password:
  theme_id:
  store: your-shop.myshopify.com
  ignore_files:
    settings_data.json
    mix-manifest.json